AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api

  Sample SAM Template for api
  
Globals:
  Function:
    Timeout: 3
    Layers:
      - !Ref BaseLayer

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/echo/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /echo
            Method: get

  ### ================
  ### Layers
  ### ================

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: base-layer
      Description: Base dependecies
      ContentUri: src/layers/base/
      CompatibleRuntimes:
        - nodejs8.10
        - nodejs10.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
